config/routes.rb
Rails.application.routes.draw do

  # manually add the refile route to work with our catch-all route
  mount Refile.app, at: "/attachments", as: :refile_app

  root :to => 'tickets#index'

  resources :tickets, :only => [:new, :create, :show, :index]

  # need this because Rails `rescue_from` doesn't catch ActionController::RoutingError
  unless Rails.env.development?
    match '*path',  :to => 'application#render_404', :via => :all
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attachment :image

  validates :title, :image, :presence => true

  before_save :store_gps_coordinates

  private

  def store_gps_coordinates
    if image_exifr.gps.present?
      self.lat = image_exifr.gps.latitude
      self.lng = image_exifr.gps.longitude
    end
  end

  def image_exifr
    @image_exifr ||= EXIFR::JPEG.new(image.to_io)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  def index
    @tickets = Ticket.all
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)

    if @ticket.save
      redirect_to tickets_path, :notice => "Ticket created!"
    else
      render :new
    end
  end

  def show
    @ticket = Ticket.find_by_id!(params[:id])
  end

  private

  def ticket_params
    params.require(:ticket).permit(:title, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExifTest</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/tickets/index.html.erb
<div class="row text-center">
  <h1>Tickets</h1>
</div>
<div class="row text-center">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <%= link_to 'New Ticket', new_ticket_path %>
    <ul>
      <% @tickets.each do |ticket| %>
        <li>
          <p><%= link_to ticket.title, ticket_path(ticket.id) %></p>
          <p><%= attachment_image_tag(ticket, :image, :fill, 300, 300) %></p>
          <p><%= 'Has Location' if ticket.lat.present? %></p>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/tickets/new.html.erb
<div class="row text-center">
  <h1>New Ticket</h1>
</div>
<div class="row text-center">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <%= form_for @ticket do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= f.attachment_field :image %>
      <%= f.submit %>
    <% end %>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/tickets/show.html.erb
<div class="row text-center">
  <h1><%= @ticket.title %></h1>
</div>
<div class="row text-center">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <p><%= image_tag attachment_url(@ticket, :image, :fill, 300, 300) %></p>
    <p><%= link_to 'Back to all tickets', tickets_path %></p>
    <p><img src="https://maps.googleapis.com/maps/api/staticmap?center=<%= @ticket.lat %>,<%= @ticket.lng %>&amp;zoom=12&amp;size=600x300&amp;markers=<%= @ticket.lat %>,<%= @ticket.lng %>"></p>
  </div>
  <div class="col-md-3"></div>
</div>